app_supp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^calendar/', include('app_supp_calendar.urls', namespace='calendar')),
    url(r'^', include('app_supp_global.urls', namespace='global')),
    url(r'^shifts/', include('app_supp_shifts.urls', namespace='shifts')),
    url(r'^teams/', include('app_supp_teams.urls', namespace='teams')),
    url(r'^tickets/', include('app_supp_tickets.urls', namespace='tickets')),
    url(r'^upload/', include('app_supp_upload.urls', namespace='upload')),
    url(r'^users/', include('app_supp_users.urls', namespace='users')),
]
urlpatterns += [url(r'^accounts/', include('django.contrib.auth.urls'))]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_supp_global/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^landing-page/$', views.landing_page, name='landing_page'),
]

app_supp_teams/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/detail/$', views.team_detail, name='team_detail'),
    url(r'^(?P<pk>\d+)/edit/membership/$', views.edit_membership, name='edit_membership'),
    url(r'^(?P<team_pk>\d+)/manager/add/(?P<profile_pk>\d+)/$', views.add_manager, name='add_manager'),
    url(r'^(?P<team_pk>\d+)/manager/remove/(?P<profile_pk>\d+)/$', views.remove_manager, name='remove_manager'),
    url(r'^(?P<team_pk>\d+)/member/add/(?P<profile_pk>\d+)/$', views.add_member, name='add_member'),
    url(r'^(?P<team_pk>\d+)/member/remove/(?P<profile_pk>\d+)/$', views.remove_member, name='remove_member'),
]

app_supp_users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^profile/create/$', views.create_profile, name='create_profile'),
    url(r'^admin/$', views.user_admin, name='user_admin'),
    url(r'^edit/(?P<pk>\d+)/$', views.user_edit, name='user_edit'),
    url(r'^admin/profile/(?P<team_pk>\d+)/create/(?P<user_pk>\d+)/$', views.admin_profile_create, name='admin_profile_create'),
    url(r'^admin/user/(?P<team_pk>\d+)/create/$', views.admin_user_create, name='admin_user_create'),
    url(r'^(?P<user_pk>\d+)/detail/$', views.user_detail, name='user_detail'),
]

app_supp_users/models.py
from django.contrib.auth.models import User
from django.utils import timezone
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile')
    job_title = models.CharField(max_length=25)
    job_description = models.CharField(max_length=200)
    start_date = models.DateField(default=timezone.now)
    end_date = models.DateField(blank=True, null=True)
    teams = models.ManyToManyField(
        'app_supp_teams.Team',
        related_name='members',
        blank=True
    )

    def __str__(self):
        return '%s %s' % (self.user.first_name, self.user.last_name)


#Could be used to accept/reject memebership offers for managing people
class Management(models.Model):
    manager = models.ForeignKey(User, related_name='workers')
    user = models.ForeignKey(User, related_name='managers')
    #accepted = models.BooleanField(default=False)
    accepted_date = models.DateTimeField(blank=True, null=True)
    rejected_date = models.DateTimeField(blank=True, null=True)
    invite_message = models.CharField(max_length=250, default='Manager Invite')

app_supp_users/forms.py
from django.forms import ModelForm
from django.contrib.auth.models import User

from .models import Profile

class UserForm(ModelForm):

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'password',
            'date_joined',
        ]




class ProfileForm(ModelForm):

    class Meta:
        model = Profile
        fields = [
            'job_title',
            'job_description',
            'start_date',
            'end_date',
        ]

app_supp_users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist

from .forms import ProfileForm, UserForm
from app_supp_teams.models import Team

#Maybe set it to go from team page
#Stop reg users from creating profiles
@login_required()
def admin_user_create(request, team_pk):
    team = get_object_or_404(Team, pk=team_pk)
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
        return redirect('users:admin_profile_create', user_pk=user.pk, team_pk=team_pk)
    else:
        form = UserForm()
    return render(
        request,
        'app_supp_users/admin_user_create.html',
        {'form': form,
        'team': team,}
    )


@login_required()
def admin_profile_create(request, team_pk, user_pk):
    team = get_object_or_404(Team, pk=team_pk)
    user = get_object_or_404(User, pk=user_pk)
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            profile = form.save(commit=False)
            profile.user = user
            profile.save()
            if not profile.teams.filter(members=profile).exists():
                profile.teams.add(team)
        return redirect('users:user_detail', user_pk=user.pk)
    else:
        form = ProfileForm()
    return render(
        request,
        'app_supp_users/admin_profile_create.html',
        {'form': form,
        'user': user,
        'team': team,}
    )


@login_required
def user_detail(request, user_pk):
    redirect('global:home_page')


@login_required()
def create_profile(request):    #Note: Only for creating 'own' profile
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            try:
                request.user.profile
            except ObjectDoesNotExist:
                profile = form.save(commit=False)
                profile.user = request.user
                profile.save()
            return redirect('global:home_page')
    else:
        form = ProfileForm()
    return render(
        request,
        'app_supp_users/create_profile.html',
        {'user': request.user,
        'form': form}
    )


@login_required()
def user_admin(request):
    try:
        request.user.profile
    except ObjectDoesNotExist:
        return redirect('users:create_profile')
    return render(
        request,
        'app_supp_users/user_admin.html',
        {'user': request.user,
        'profile': request.user.profile,}
    )


#Note: maybe make into a user_edit_self function
@login_required
def user_edit(request, pk):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            pass
    return None

app_supp_users/templates/app_supp_users/admin_profile_create.html
<p>Test template_create</p>

{% extends "app_supp_shifts/base.html" %}

{% block content %}
  <a href="{% url 'teams:team_detail' pk=team.pk %}">Team Detail</a>
  <p>{{ user.get_full_name }}</p>
  <h1>Configure Template</h1>
  <form method="POST" class="post-form">{% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="save btn btn-default">Save</button>
  </form>

{% endblock %}

app_supp_users/templates/app_supp_users/admin_user_create.html
<p>Test template_create</p>

{% extends "app_supp_users/base.html" %}

{% block content %}
  <a href="{% url 'teams:team_detail' pk=team.pk %}">Team Detail</a>
  <h1>Configure User</h1>
  <form method="POST" class="post-form">{% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="save btn btn-default">Save</button>
  </form>

{% endblock %}

app_supp_users/templates/app_supp_users/base.html
<a href="{% url 'global:landing_page' %}">Home</a>

<body>
  <p>
    Name: {{ user.first_name }} {{ user.last_name }}
  </p>
  <p>
    Job Title: {{ profile.job_title }}
  </p>
  <p>
    Job Description: {{ profile.job_description }}
  </p>
  <p>
    Start Date: {{ profile.start_date }}
  </p>
  <p>
    End Date:
    {% if profile.end_date %}
      {{ profile.start_date }}
    {% else %}
      No End Date Specified
    {% endif %}
  </p>
</body>

{% block content %}

{% endblock %}

app_supp_users/templates/app_supp_users/create_profile.html
<p>Test create_profile</p>

{% extends "app_supp_users/base.html" %}

{% block content %}
  <h1>Create User Profile</h1>
  <form method="POST" class="post-form">{% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="save btn btn-default">Save</button>
  </form>

{% endblock %}

app_supp_users/templates/app_supp_users/user_admin.html
{% extends "app_supp_users/base.html" %}

{% block content %}

  <a href="{% url 'users:user_edit' pk=user.pk %}">Edit User Settings</a>

{% endblock %}