app_supp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^calendar/', include('app_supp_calendar.urls', namespace='calendar')),
    url(r'^', include('app_supp_global.urls', namespace='global')),
    url(r'^shifts/', include('app_supp_shifts.urls', namespace='shifts')),
    url(r'^teams/', include('app_supp_teams.urls', namespace='teams')),
    url(r'^tickets/', include('app_supp_tickets.urls', namespace='tickets')),
    url(r'^upload/', include('app_supp_upload.urls', namespace='upload')),
    url(r'^users/', include('app_supp_users.urls', namespace='users')),
]
urlpatterns += [url(r'^accounts/', include('django.contrib.auth.urls'))]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_supp_global/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^landing-page/$', views.landing_page, name='landing_page'),
]

app_supp_shifts/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^template/create/(?P<pk>\d+)/$', views.template_create, name='template_create'),
    url(r'^template/edit/(?P<pk>\d+)/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/calendar/$',
        views.template_edit_calendar,
        name='template_edit_calendar'
    ),
    url(r'^template/deactivate/(?P<pk>\d+)/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/calendar/$',
        views.template_deactivate_calendar,
        name='template_deactivate_calendar'
    ),
    url(r'^template/activate/(?P<pk>\d+)/$', views.template_activate, name='template_activate'),
    url(r'^template/deactivate/(?P<pk>\d+)/$', views.template_deactivate, name='template_deactivate'),
    url(r'^template/delete/(?P<pk>\d+)/$', views.template_delete, name='template_delete'),
    url(r'^template/edit/(?P<pk>\d+)/$', views.template_edit, name='template_edit'),
    url(r'^shift/create/(?P<pk>\d+)/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        views.shift_create,
        name='shift_create'
    ),
    url(r'^shift/assign/(?P<pk>\d+)/(?P<year>[0-9]{4})/(?P<month>[0-9]+)/(?P<day>[0-9]+)/$',
        views.shift_assign,
        name='shift_assign'
    ),
]

app_supp_teams/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/detail/$', views.team_detail, name='team_detail'),
    url(r'^(?P<pk>\d+)/edit/membership/$', views.edit_membership, name='edit_membership'),
    url(r'^(?P<team_pk>\d+)/manager/add/(?P<profile_pk>\d+)/$', views.add_manager, name='add_manager'),
    url(r'^(?P<team_pk>\d+)/manager/remove/(?P<profile_pk>\d+)/$', views.remove_manager, name='remove_manager'),
    url(r'^(?P<team_pk>\d+)/member/add/(?P<profile_pk>\d+)/$', views.add_member, name='add_member'),
    url(r'^(?P<team_pk>\d+)/member/remove/(?P<profile_pk>\d+)/$', views.remove_member, name='remove_member'),
]

app_supp_upload/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^team/(?P<pk>\d+)/manage-documents/$', views.manage_documents, name='manage_documents'),
    url(r'^file/(?P<pk>\d+)/upload/$', views.upload_file, name='upload_file'),
    url(r'^file/(?P<pk>\d+)/delete/$', views.delete_file, name='delete_file'),
    url(r'^file/(?P<pk>\d+)/deactivate/$', views.deactive_file, name='deactive_file'),
    url(r'^file/(?P<pk>\d+)/activate/$', views.active_file, name='active_file'),
]

app_supp_users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^profile/create/$', views.create_profile, name='create_profile'),
    url(r'^admin/$', views.user_admin, name='user_admin'),
    url(r'^edit/(?P<pk>\d+)/$', views.user_edit, name='user_edit'),
    url(r'^admin/profile/(?P<team_pk>\d+)/create/(?P<user_pk>\d+)/$', views.admin_profile_create, name='admin_profile_create'),
    url(r'^admin/user/(?P<team_pk>\d+)/create/$', views.admin_user_create, name='admin_user_create'),
    url(r'^(?P<user_pk>\d+)/detail/$', views.user_detail, name='user_detail'),
]

app_supp_teams/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import Group, User


class Team(models.Model):
    #Note: might need just one admin to do membership changes.
    #Avoid multiple people editing db at once(?)
    #manager = models.ForeignKey(User, related_name='managed_teams')
    #Could limit the size of the manager group to 1(?)
    manager_group = models.OneToOneField(Group, related_name='team', null=True)        #use to check if User is in Group. Allow editing etc...
    team_name = models.CharField(max_length=50)
    start_date = models.DateField(default=timezone.now)
    active = models.BooleanField(default=True)
    deleted_date = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.team_name


    def create_manager_group(self):
        if hasattr(self, manager_group):
            if self.manager_group.name == self.manager_group_name:
                pass
            else:
                self.manager_group.name = self.manager_group_name
                self.manager_group.save()
        else:
            manager_group = Group(name = self.manager_group_name)
            manager_group.save()
            self.manager_group = manager_group
            self.save()


    def start_time(self):
        return min(
            team.shift_templates.filter(
                active=True,
            ).exclude(
                deleted_date__lte=timezone.now(),
                start_date__gte=timezone.now().date,
                end_date__lte=timezone.now().date,
            ).values_list(
                'start_time', flat=True
            ), default=None
        )


    def end_time(self):
        return max(
            team.shift_templates.filter(
                active=True,
            ).exclude(
                deleted_date__lte=timezone.now(),
                start_date__gte=timezone.now().date,
                end_date__lte=timezone.now().date,
            ).values_list(
                'end_time', flat=True
            ), default=None
        )


#Could be used to accept/reject memebership offers for teams
class Membership(models.Model):
    team = models.ForeignKey(Team, related_name='memberships')
    user = models.ForeignKey(User, related_name='memberships')
    #accepted = models.BooleanField(default=False)
    accepted_date = models.DateTimeField(blank=True, null=True)
    rejected_date = models.DateTimeField(blank=True, null=True)
    invite_message = models.CharField(max_length=250, default='Team Invite')

app_supp_teams/views.py
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

from .models import Team
from app_supp_users.models import Profile

@login_required
def team_detail(request, pk):
    team = get_object_or_404(Team, pk=pk)
    active_profiles = team.members.filter(
        user__is_active=True
    )
    manager_profiles = active_profiles.filter(
        user__in=team.manager_group.user_set.all(),
    ).order_by('user__last_name')
    member_profiles = active_profiles.exclude(
        user__in=team.manager_group.user_set.all(),
    ).order_by('user__last_name')
    active_templates = team.shift_templates.filter(
        active=True,
    ).exclude(
        deleted_date__lte=timezone.now()
    )
    inactive_templates = team.shift_templates.filter(
        active=False,
    ).exclude(
        deleted_date__lte=timezone.now()
    )
    return render(
        request,
        'app_supp_teams/team_detail.html',
        {'team': team,
        'user': request.user,
        'profile': request.user.profile,
        'date': timezone.now().date,
        'managers': manager_profiles,
        'members': member_profiles,
        'active_templates': active_templates,
        'inactive_templates': inactive_templates,}
    )


@login_required
def edit_membership(request, pk):
    team = get_object_or_404(Team, pk=pk)
    active_profiles = team.members.filter(
        user__is_active=True
    )
    manager_profiles = active_profiles.filter(
        user__in=team.manager_group.user_set.all(),
    ).order_by('user__last_name')
    member_profiles = active_profiles.exclude(
        user__in=team.manager_group.user_set.all(),
    ).order_by('user__last_name')
    non_member_profiles = Profile.objects.filter(
        user__is_active=True,
    ).exclude(
        pk__in=active_profiles.values_list('pk', flat=True),
    ).order_by('user__last_name')
    return render(
        request,
        'app_supp_teams/edit_membership.html',
        {'team': team,
        'user': request.user,
        'profile': request.user.profile,
        'date': timezone.now().date,
        'managers': manager_profiles,
        'members': member_profiles,
        'non_members': non_member_profiles,}
    )


@login_required
def add_manager(request, team_pk, profile_pk):
    team = get_object_or_404(Team, pk=team_pk)
    profile = get_object_or_404(Profile, pk=profile_pk)
    profile.user.groups.add(team.manager_group)
    return edit_membership(request, pk=team.pk)


@login_required
def remove_manager(request, team_pk, profile_pk):
    team = get_object_or_404(Team, pk=team_pk)
    profile = get_object_or_404(Profile, pk=profile_pk)
    if team.manager_group.user_set.count() > 1:
        profile.user.groups.remove(team.manager_group)
    else:
        pass
    return edit_membership(request, pk=team.pk)


@login_required
def add_member(request, team_pk, profile_pk):
    team = get_object_or_404(Team, pk=team_pk)
    profile = get_object_or_404(Profile, pk=profile_pk)
    profile.teams.add(team)
    return edit_membership(request, pk=team.pk)


@login_required
def remove_member(request, team_pk, profile_pk):
    team = get_object_or_404(Team, pk=team_pk)
    profile = get_object_or_404(Profile, pk=profile_pk)
    profile.teams.remove(team)
    return edit_membership(request, pk=team.pk)

app_supp_teams/templates/app_supp_teams/base.html
<html>
  <head>
    <h1>{{ team.team_name }}</h1>
  </head>
  <body>
    <div class="details-heading">
      <p><a href="{% url 'global:landing_page' %}">Landing Page</a></p>
    </div>
    <div class="details">
      <p>Team Start Date: {{ team.start_date }}</p>
    </div>
  </body>
{% block content %}


{% endblock %}

app_supp_teams/templates/app_supp_teams/edit_membership.html
{% extends "app_supp_teams/base.html" %}

{% block content %}

  <a href="{% url 'teams:team_detail' pk=team.pk %}">Team Detail</a>
  <p><a href="{% url 'users:admin_user_create' team_pk=team.pk %}">Create New Member</a></p>
  <div class="details-heading">
    <h1>Edit Team Membership</h1>
    <h1>Managers</h1>
  </div>
  <div class="details">
    {% for profile in managers %}
      <p>
        {{ profile.user.first_name }}
        {{ profile.user.last_name }} -
        {{ profile.job_title }}
        <a href="{% url 'teams:remove_manager' team_pk=team.pk profile_pk=profile.pk %}">Remove Manager</a>
      </p>
    {% endfor %}
  </div>
  <div class="details-heading">
    <h1>Members</h1>
  </div>
  <div class="details">
    {% for profile in members %}
      <p>
        {{ profile.user.first_name }}
        {{ profile.user.last_name }} -
        {{ profile.job_title }}
        <a href="{% url 'teams:add_manager' team_pk=team.pk profile_pk=profile.pk %}">Make Manager</a>
        <a href="{% url 'teams:remove_member' team_pk=team.pk profile_pk=profile.pk %}">Remove Member</a>
      </p>
    {% endfor %}
  </div>
  <div class="details-heading">
    <h1>Non-Members</h1>
  </div>
  <div class="details">
    {% for profile in non_members %}
      <p>
        {{ profile.user.first_name }}
        {{ profile.user.last_name }} -
        {{ profile.job_title }}
        <a href="{% url 'teams:add_member' team_pk=team.pk profile_pk=profile.pk %}">Add Member</a>
      </p>
    {% endfor %}
  </div>
{% endblock %}

app_supp_teams/templates/app_supp_teams/team_detail.html
{% extends "app_supp_teams/base.html" %}

{% block content %}

  <body>
    <p><a href="{% url 'calendar:month_view' pk=team.pk year=date.year month=date.month day=date.day %}">Month Calendar</a></p>
    <p><a href="{% url 'shifts:template_create' pk=team.pk %}">Create Shift Template</a></p>
    <p><a href="{% url 'teams:edit_membership' pk=team.pk %}">Edit Team Membership</a></p>
    <p><a href="{% url 'upload:manage_documents' pk=team.pk %}">Manage Documents</a></p>
    <div class="details-heading">
      <h1>Managers</h1>
    </div>
    <div class="details">
      {% for profile in managers %}
        <p>
          {{ profile.user.first_name }}
          {{ profile.user.last_name }} -
          {{ profile.job_title }}
        </p>
        <p>
          Start Date: {{ profile.start_date }}
        </p>
      {% empty %}
        <p>No Managers</p>
      {% endfor %}
    </div>
    <div class="details-heading">
      <h1>Members</h1>
    </div>
    <div class="details">
      {% for profile in members %}
        <p>
          {{ profile.user.first_name }}
          {{ profile.user.last_name }} -
          {{ profile.job_title }}
        </p>
        <p>
          Start Date: {{ profile.start_date }}
        </p>
        <p>
          {% if profile.end_date %}
            {{ profile.end_date }}
          {% endif %}
        </p>
      {% empty %}
        <p>No Members</p>
      {% endfor %}
    </div>
    <div class="details-heading">
      {% if active_templates %}
        <h1>Active Shifts</h1>
      {% endif %}
    </div>
    <div class="details">
      {% for shift in active_templates %}
        <p>
          Shift Name: {{ shift.shift_name }}
          <a href="{% url 'shifts:template_edit' pk=shift.pk %}">Edit</a>
          <a href="{% url 'shifts:template_deactivate' pk=shift.pk %}">Deactivate</a>
        </p>
        {% if shift.start_date %}
          <p>
            Start Date: {{ shift.start_date }}
          </p>
        {% endif %}
        {% if shift.end_date %}
          <p>
            End Date: {{ shift.end_date }}
          </p>
        {% endif %}
        <p>
          {{ shift.start_time }} - {{ shift.end_time }}
        </p>
      {% empty %}
        <h1>No Active Shift Patterns</h1>
      {% endfor %}
    </div>
    <div class="details-heading">
      {% if inactive_templates %}
        <h1>Inactive Shifts</h1>
      {% endif %}
    </div>
    <div class="details">
      {% for shift in inactive_templates %}
        <p>
          Shift Name: {{ shift.shift_name }}
          <a href="{% url 'shifts:template_edit' pk=shift.pk %}">Edit</a>
          <a href="{% url 'shifts:template_activate' pk=shift.pk %}">Activate</a>
          <a href="{% url 'shifts:template_delete' pk=shift.pk %}">Delete</a>
        </p>
        {% if shift.start_date %}
          <p>
            Start Date: {{ shift.start_date }}
          </p>
        {% endif %}
        {% if shift.end_date %}
          <p>
            End Date: {{ shift.end_date }}
          </p>
        {% endif %}
        <p>
          {{ shift.start_time }} - {{ shift.end_time }}
        </p>
      {% endfor %}
    </div>
  </body>

{% endblock %}