app_supp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^calendar/', include('app_supp_calendar.urls', namespace='calendar')),
    url(r'^', include('app_supp_global.urls', namespace='global')),
    url(r'^shifts/', include('app_supp_shifts.urls', namespace='shifts')),
    url(r'^teams/', include('app_supp_teams.urls', namespace='teams')),
    url(r'^tickets/', include('app_supp_tickets.urls', namespace='tickets')),
    url(r'^upload/', include('app_supp_upload.urls', namespace='upload')),
    url(r'^users/', include('app_supp_users.urls', namespace='users')),
]
urlpatterns += [url(r'^accounts/', include('django.contrib.auth.urls'))]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_supp_calendar/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^view/(?P<pk>\d+)/month/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]+)/$', views.month_view, name='month_view'),
    url(r'^view/(?P<pk>\d+)/week/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]+)/$', views.week_view, name='week_view'),
    url(r'^view/(?P<pk>\d+)/day/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/(?P<day>[0-9]+)/$', views.day_view, name='day_view'),
]

app_supp_global/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^landing-page/$', views.landing_page, name='landing_page'),
]

app_supp_teams/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/detail/$', views.team_detail, name='team_detail'),
    url(r'^(?P<pk>\d+)/edit/membership/$', views.edit_membership, name='edit_membership'),
    url(r'^(?P<team_pk>\d+)/manager/add/(?P<profile_pk>\d+)/$', views.add_manager, name='add_manager'),
    url(r'^(?P<team_pk>\d+)/manager/remove/(?P<profile_pk>\d+)/$', views.remove_manager, name='remove_manager'),
    url(r'^(?P<team_pk>\d+)/member/add/(?P<profile_pk>\d+)/$', views.add_member, name='add_member'),
    url(r'^(?P<team_pk>\d+)/member/remove/(?P<profile_pk>\d+)/$', views.remove_member, name='remove_member'),
]

app_supp_users/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^profile/create/$', views.create_profile, name='create_profile'),
    url(r'^admin/$', views.user_admin, name='user_admin'),
    url(r'^edit/(?P<pk>\d+)/$', views.user_edit, name='user_edit'),
    url(r'^admin/profile/(?P<team_pk>\d+)/create/(?P<user_pk>\d+)/$', views.admin_profile_create, name='admin_profile_create'),
    url(r'^admin/user/(?P<team_pk>\d+)/create/$', views.admin_user_create, name='admin_user_create'),
    url(r'^(?P<user_pk>\d+)/detail/$', views.user_detail, name='user_detail'),
]

app_supp_global/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.utils import timezone

from app_supp_teams.models import Team

@login_required
def home_page(request):
    return redirect('global:landing_page')

@login_required
def landing_page(request):
    try:
        request.user.profile
    except ObjectDoesNotExist:
        return redirect('users:create_profile')
    date = timezone.now().date
    member_teams = request.user.profile.teams.filter(
        active=True
    )
    non_member_teams = Team.objects.filter(
        active=True,
    ).exclude(pk__in=member_teams.values_list('id', flat=True))
    return render(
        request,
        'app_supp_global/landing_page.html',
        {'user': request.user,
        'profile': request.user.profile,
        'date': date,
        'member_teams': member_teams,
        'non_member_teams': non_member_teams,}
    )

app_supp_global/templates/app_supp_global/base.html
<p>Name: {{ user.get_full_name }}</p>
<p>Job Title: {{ profile.job_title }}</p>
<p>Last Login: {{ user.last_login }}</p>

{% block content %}

{% endblock %}

app_supp_global/templates/app_supp_global/landing_page.html
{% extends "app_supp_global/base.html" %}

{% block content %}

  <h1>User Admin</h1>
  <p><a href="{% url 'users:user_admin' %}">Go To User Admin</a></p>


  <h1>Member Teams</h1>
  {% for team in member_teams %}
    <p>
      {{ team.team_name }}
      <a href="{% url 'calendar:month_view' pk=team.pk year=date.year month=date.month day=date.day %}">Month Calendar</a>
      <a href="{% url 'teams:team_detail' pk=team.pk %}">Team Detail</a>
    </p>
  {% empty %}
    <p>No Member Teams</p>
  {% endfor %}
  {% if non_member_teams %}
    <h1>Non-Member Teams</h1>
    {% for team in non_member_teams %}
      <p>
        {{ team.team_name }}
        <a href="{% url 'calendar:month_view' pk=team.pk year=date.year month=date.month day=date.day %}">Month Calendar</a>
        <a href="{% url 'teams:team_detail' pk=team.pk %}">Team Detail</a>
      </p>
    {% endfor %}
  {% endif %}

{% endblock %}