app_supp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^calendar/', include('app_supp_calendar.urls', namespace='calendar')),
    url(r'^', include('app_supp_global.urls', namespace='global')),
    url(r'^shifts/', include('app_supp_shifts.urls', namespace='shifts')),
    url(r'^teams/', include('app_supp_teams.urls', namespace='teams')),
    url(r'^tickets/', include('app_supp_tickets.urls', namespace='tickets')),
    url(r'^upload/', include('app_supp_upload.urls', namespace='upload')),
    url(r'^users/', include('app_supp_users.urls', namespace='users')),
]
urlpatterns += [url(r'^accounts/', include('django.contrib.auth.urls'))]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_supp_global/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^$', views.home_page, name='home_page'),
    url(r'^landing-page/$', views.landing_page, name='landing_page'),
]

app_supp_teams/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^(?P<pk>\d+)/detail/$', views.team_detail, name='team_detail'),
    url(r'^(?P<pk>\d+)/edit/membership/$', views.edit_membership, name='edit_membership'),
    url(r'^(?P<team_pk>\d+)/manager/add/(?P<profile_pk>\d+)/$', views.add_manager, name='add_manager'),
    url(r'^(?P<team_pk>\d+)/manager/remove/(?P<profile_pk>\d+)/$', views.remove_manager, name='remove_manager'),
    url(r'^(?P<team_pk>\d+)/member/add/(?P<profile_pk>\d+)/$', views.add_member, name='add_member'),
    url(r'^(?P<team_pk>\d+)/member/remove/(?P<profile_pk>\d+)/$', views.remove_member, name='remove_member'),
]

app_supp_tickets/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^file/(?P<pk>\d+)/process/$', views.map_docfile, name='map_docfile'),
]

app_supp_upload/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^team/(?P<pk>\d+)/manage-documents/$', views.manage_documents, name='manage_documents'),
    url(r'^file/(?P<pk>\d+)/upload/$', views.upload_file, name='upload_file'),
    url(r'^file/(?P<pk>\d+)/delete/$', views.delete_file, name='delete_file'),
    url(r'^file/(?P<pk>\d+)/deactivate/$', views.deactive_file, name='deactive_file'),
    url(r'^file/(?P<pk>\d+)/activate/$', views.active_file, name='active_file'),
]

app_supp_upload/models.py
from django.db import models
from django.forms import ModelForm

class Upload(models.Model):
    docfile = models.FileField("Document", upload_to="uploads/")
    file_name = models.CharField(max_length=100)
    upload_datetime = models.DateTimeField(auto_now_add=True)
    team = models.ForeignKey('app_supp_teams.Team', related_name='uploads')
    active = models.BooleanField(default=True)

app_supp_upload/forms.py
from django.forms import ModelForm

from .models import Upload

class UploadForm(ModelForm):
    class Meta:
        model = Upload
        fields = (
            'docfile',
            'file_name',
            'active',
        )

app_supp_upload/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

import os

from .models import Upload
from .forms import UploadForm
from app_supp_teams.models import Team

@login_required()
def manage_documents(request, pk):
    team = get_object_or_404(Team, pk=pk)
    active_uploads = team.uploads.filter(
        active=True
    ).order_by(
        '-upload_datetime'
    )
    inactive_uploads = team.uploads.filter(
        active=False
    ).order_by(
        '-upload_datetime'
    )
    return render(
        request,
        'app_supp_upload/manage_documents.html',
        {'team': team,
        'active_uploads': active_uploads,
        'archived_uploads': inactive_uploads,}
    )


@login_required()
def upload_file(request, pk):
    team = get_object_or_404(Team, pk=pk)
    if request.method=="POST":
        form = UploadForm(request.POST, request.FILES)
        if form.is_valid():
            data_file = form.save(commit=False)
            data_file.team = team
            data_file.save()
            return manage_documents(request, pk=team.pk)
    else:
        form=UploadForm()
    files=Upload.objects.filter(
        team=team,
    ).order_by(
        '-upload_datetime',
    )[:5]
    return render(
        request,
        'app_supp_upload/upload_file.html',
        {'form':form,
        'files':files,
        'team': team,}
    )


@login_required()
def delete_file(request, pk):
    upload = get_object_or_404(Upload, pk=pk)
    team = upload.team
    file_location = upload.docfile.path
    upload.delete()
    os.remove(file_location)
    return manage_documents(request, pk=team.pk)


@login_required()
def active_file(request, pk):
    upload = get_object_or_404(Upload, pk=pk)
    team = upload.team
    upload.active = True
    upload.save()
    return manage_documents(request, pk=team.pk)


@login_required()
def deactive_file(request, pk):
    upload = get_object_or_404(Upload, pk=pk)
    team = upload.team
    upload.active = False
    upload.save()
    return manage_documents(request, pk=team.pk)

app_supp_upload/templates/app_supp_upload/base.html
<p>Name: {{ user.get_full_name }}</p>
<p>Job Title: {{ user.profile.job_title }}</p>
<p>Last Login: {{ user.last_login }}</p>
<div class="details-heading">
  <p><a href="{% url 'global:landing_page' %}">Landing Page</a></p>
</div>

{% block content %}

{% endblock %}

app_supp_upload/templates/app_supp_upload/manage_documents.html
{% extends "app_supp_upload/base.html" %}

{% block content %}

  <h1>{{ team.team_name }}</h1>
  <a href="{% url 'teams:team_detail' pk=team.pk %}">Team Detail</a>
  <h1>Document Managment</h1>
  <a href="{% url 'upload:upload_file' pk=team.pk %}">Upload Document</a>

  <h1>Current Uploads</h1>
    {% for upload in active_uploads %}
      <p>
        <a href="{% url 'upload:deactive_file' pk=upload.pk %}">Deactivate</a>
        <a href="{{ upload.docfile.url }}">Download</a>
        <a href="{% url 'tickets:map_docfile' pk=upload.pk %}">Process</a>
        File Name: {{ upload.file_name }}
      </p>
    {% endfor %}
    <h1>Archived Uploads</h1>
      {% for upload in archived_uploads %}
        <p>
          <a href="{% url 'upload:active_file' pk=upload.pk %}">Activate</a>
          <a href="{% url 'upload:delete_file' pk=upload.pk %}">Delete</a>
          File Name: {{ upload.file_name }}
        </p>
      {% endfor %}

{% endblock %}

app_supp_upload/templates/app_supp_upload/upload_file.html
<h1>{{ team.team_name }}</h1>
<a href="{% url 'upload:manage_documents' pk=team.pk %}">Manage Documents</a>

<div style="padding:40px;margin:40px;border:1px solid #ccc">
    <h1>document</h1>
    <form action="#" method="post" enctype="multipart/form-data">
        {% csrf_token %} {{form}}
        <input type="submit" value="Upload" />
    </form>
    <p>Last 5 Uploads</p>
    {% for file in files %}
        {{forloop.counter}}.<a href="{{ file.docfile.url }}">{{ file.docfile.name }}</a>
        ({{docfile.upload_datetime}})<hr />
    {% endfor %}
</div>